

find statistics about the one2many, many2many, many2one genes.
how much data do we have about them?
```{r}
#!/Local/md_shenorr/R-3.2.0/bin/Rscript

library(readr)
library(dplyr)
require(ggplot2)
require(plyr)
# devtools::install_github('shenorrLab/FIT.mouse2man') #TODO ask to install

data <- readRDS("C:/Users/inbal/Google Drive/shen-orr/all_comp_files.rds")
```



```{r}
one2many_many2many_many2one <- data %>% filter(ortholog_type == "n:m" | ortholog_type == "n:1" | ortholog_type == "1:m")
one2many_many2many_many2one_mouse =unique(one2many_many2many_many2one$mouse_entrez_ID)
one2many_many2many_many2one_human =unique(one2many_many2many_many2one$human_entrez_ID)
# data("AllData_V2.0",package="FIT.mouse2man")
# write(one2many_many2many_many2one_human, "/storage/md_shenorr/inbaltz/one2many_many2many_many2one_human.txt")

#one2many
one2many <- data %>% filter(ortholog_type == "1:m")
mouse_geneList = unique(one2many$mouse_entrez_ID)
human_geneList = unique(one2many$human_entrez_ID)

#some genes are annotated as one2many but because of missing data are in our case one2one. here we filter them out.
for (mouse_gene in mouse_geneList){
  if (length(unique((data %>% filter(mouse_entrez_ID==mouse_gene))$human_entrez_ID)) < 2)
    mouse_geneList=mouse_geneList[mouse_geneList != mouse_gene];
}

#create histogram- for each mouse gene' how many diseases do we have data on:
disease_histogram=c()
for (mouse_gene in mouse_geneList){
  disease_histogram=c(disease_histogram, length(unique((data %>% filter(mouse_entrez_ID==mouse_gene))$disease)))
}
hist(disease_histogram,main = "number of diseases which contain data of each gene",
     xlab="# diseases")
```

```{r}
for_plot_one2many_compfiles=data.frame()
for_plot_one2many_disease=data.frame()
for (mouse_gene in mouse_geneList){
  human_orthologs = unique((data %>% filter(mouse_entrez_ID == mouse_gene))$human_entrez_ID)
  count_compfiles_per_human_ortholog=c()
  count_disease_per_human_ortholog=c()
  for (i in 1:length(human_orthologs)){
    count_compfiles_per_human_ortholog[i]=length(unique((data %>% filter(mouse_entrez_ID == mouse_gene & human_entrez_ID == human_orthologs[i]))$comp_file))
    count_disease_per_human_ortholog[i]=length(unique((data %>% filter(mouse_entrez_ID == mouse_gene & human_entrez_ID == human_orthologs[i]))$disease))
  }
  #compfile plot
  x = replicate(length(count_compfiles_per_human_ortholog),length(unique((data %>% filter(mouse_entrez_ID == mouse_gene))$comp_file)))
  l <- data.frame(x,count_compfiles_per_human_ortholog)
  l["group"] =mouse_gene 
  for_plot_one2many_compfiles <- rbind(for_plot_one2many_compfiles,l)
  #disease plot
  x = replicate(length(count_disease_per_human_ortholog),length(unique((data %>% filter(mouse_entrez_ID == mouse_gene))$disease)))
  l <- data.frame(x,count_disease_per_human_ortholog)
  l["group"] =mouse_gene 
  for_plot_one2many_disease <- rbind(for_plot_one2many_disease,l)
}
ggplot(data=for_plot_one2many_compfiles, aes(x=x, y=count_compfiles_per_human_ortholog, group=group))+ geom_line()+geom_point()+labs(x="#comp files mouse",y="#comp files human orthologs")+ggtitle("one2many orthologs")
ggplot(data=for_plot_one2many_disease, aes(x=x, y=count_disease_per_human_ortholog, group=group))+ geom_line()+geom_point()+labs(x="#diseases mouse",y="#diseases human orthologs")+ggtitle("one2many orthologs")
```

```{r}
#many2one
many2one <- data %>% filter(ortholog_type == "n:1")
mouse_geneList = unique(many2one$mouse_entrez_ID)
human_geneList = unique(many2one$human_entrez_ID)

for_plot_many2one_compfiles=data.frame()
for (human_gene in human_geneList){
  mouse_orthologs = unique((data %>% filter(human_entrez_ID == human_gene))$mouse_entrez_ID)
  count_compfiles_per_mouse_ortholog=c()
  for (i in 1:length(mouse_orthologs)){
    count_compfiles_per_mouse_ortholog[i]=length(unique((data %>% filter(human_entrez_ID == human_gene & mouse_entrez_ID == mouse_orthologs[i]))$comp_file))
  }
  x = replicate(length(count_compfiles_per_mouse_ortholog),length(unique((data %>% filter(human_entrez_ID == human_gene))$comp_file)))
  l <- data.frame(x,count_compfiles_per_mouse_ortholog)
  l["group"] =human_gene 
  for_plot_many2one_compfiles <- rbind(for_plot_many2one_compfiles,l)
  }
ggplot(data=for_plot_many2one_compfiles, aes(x=count_compfiles_per_mouse_ortholog, y=x, group=group))+ 
  geom_line()+
  geom_point()+
  labs(x="#comp files mouse",y="#comp files human orthologs")+
  ggtitle("many2one orthologs")
```

```{r}
#create histogram- for each mouse gene' how many diseases do we have data on:
disease_histogram=c()
for (human_gene in human_geneList){
  disease_histogram=c(disease_histogram, length(unique((data %>% filter(human_entrez_ID==human_gene))$disease)))
}
hist(disease_histogram,main = "number of diseases which contain data of each gene",
     xlab="# diseases")
```

```{r}
#many2many
many2many <- data %>% filter(ortholog_type == "n:m")
mouse_geneList = unique(many2many$mouse_entrez_ID)
plot_num_orthologs_in_group_mouse = c()
plot_num_orthologs_in_group_human = c()

plot_num_orthologs_with_data_mouse = c()
plot_num_orthologs_with_data_human = c()

for_plot=data.frame()
percent_orth_kept_after_filter = c()

while (length(mouse_geneList)>0){
  human_orthologs_group = c()
  mouse_orthologs_group = c(mouse_geneList[1])
  to_add_mouse = setdiff(unique((data %>% filter(human_entrez_ID %in% human_orthologs_group))$mouse_entrez_ID),mouse_orthologs_group)
  to_add_human = setdiff(unique((data %>% filter(mouse_entrez_ID %in% mouse_orthologs_group))$human_entrez_ID),human_orthologs_group)
  while (length(to_add_mouse)>0 | length(to_add_human)>0){
    human_orthologs_group = unique(c(human_orthologs_group,to_add_human))
    mouse_orthologs_group = unique(c(mouse_orthologs_group,to_add_mouse))
    to_add_mouse = setdiff(unique((data %>% filter(human_entrez_ID %in% human_orthologs_group))$mouse_entrez_ID),mouse_orthologs_group)
    to_add_human = setdiff(unique((data %>% filter(mouse_entrez_ID %in% mouse_orthologs_group))$human_entrez_ID),human_orthologs_group)
  }
  mouse_geneList=mouse_geneList[! mouse_geneList %in% mouse_orthologs_group]
  if(length(mouse_orthologs_group)>1 & length(human_orthologs_group)>1){
  plot_num_orthologs_in_group_mouse = c(plot_num_orthologs_in_group_mouse,length(mouse_orthologs_group))
  plot_num_orthologs_in_group_human = c(plot_num_orthologs_in_group_human,length(human_orthologs_group))
  count_comp_files_per_mouse_ortholog=c()
  count_comp_files_per_human_ortholog=c()
  
  for (i in 1:length(mouse_orthologs_group)){
    count_comp_files_per_mouse_ortholog[i]=length(unique((data %>% filter(mouse_entrez_ID == mouse_orthologs_group[i]))$comp_file))
  }
  for (i in 1:length(human_orthologs_group)){
    count_comp_files_per_human_ortholog[i]=length(unique((data %>% filter(human_entrez_ID == human_orthologs_group[i]))$comp_file))
  }
  x = c()
  y = c()
  for (i in 1:length(mouse_orthologs_group)){
    for (j in 1:length(human_orthologs_group)){
      x = c(x, count_comp_files_per_mouse_ortholog[i])
      y = c(y, count_comp_files_per_human_ortholog[j])
    }
  }
  l <- data.frame(x,y)
  l["group"] =mouse_orthologs_group[1] 
  for_plot <- rbind(for_plot,l)

  orth_with_sufficient_data = data.frame()
  for (i in 1:length(mouse_orthologs_group)){
    for (j in 1:length(human_orthologs_group)){
      orth_with_sufficient_data[i,j]= length(unique((data %>% filter(mouse_entrez_ID == mouse_orthologs_group[i] & human_entrez_ID == human_orthologs_group[j]))$comp_file))
    }
  }
  percent_orth_kept_after_filter = c(percent_orth_kept_after_filter,sum(dim(orth_with_sufficient_data[! apply(orth_with_sufficient_data < 40, 1, all), ! apply(orth_with_sufficient_data < 40, 2, all)]))/sum(dim(orth_with_sufficient_data)))
  orth_with_sufficient_data = orth_with_sufficient_data[! apply(orth_with_sufficient_data < 40, 1, all), ! apply(orth_with_sufficient_data < 40, 2, all)]
  plot_num_orthologs_with_data_mouse = c(plot_num_orthologs_with_data_mouse, dim(orth_with_sufficient_data)[1])
  plot_num_orthologs_with_data_human = c(plot_num_orthologs_with_data_human, dim(orth_with_sufficient_data)[2])
  }
}

#plot with num comp files for each group. very not clear
ggplot(data=for_plot, aes(x=x, y=y, group=group))+ geom_line()+
  geom_point()+
  labs(x="#comp files mouse",y="#comp files human orthologs")+
  ggtitle("many2many orthologs")

#plot with group sizes before filtering.
num_orth_data <- data.frame(plot_num_orthologs_in_group_human,plot_num_orthologs_in_group_mouse)
num_orth_data <- ddply(num_orth_data,.(plot_num_orthologs_in_group_human, plot_num_orthologs_in_group_mouse),nrow)
ggplot(data=num_orth_data, aes(x=plot_num_orthologs_in_group_mouse,y=plot_num_orthologs_in_group_human))+
  geom_point(aes(colour = num_orth_data$V1))+
  scale_colour_continuous( low = "blue", high = "red",name="#groups")+
  labs(x="#orthologs mouse",y="#orthologs human")+
  ggtitle("many2many group sizes")

#plot with group sizes after filtering.
num_orth_data <- data.frame(plot_num_orthologs_with_data_mouse,plot_num_orthologs_with_data_human)
num_orth_data = filter(num_orth_data, plot_num_orthologs_with_data_human > 0 | plot_num_orthologs_with_data_mouse > 0)
num_orth_data <- ddply(num_orth_data,.(plot_num_orthologs_with_data_human, plot_num_orthologs_with_data_mouse),nrow)
ggplot(data=num_orth_data, aes(x=plot_num_orthologs_with_data_mouse,y=plot_num_orthologs_with_data_human))+
  geom_point(aes(colour = num_orth_data$V1))+
  scale_colour_continuous( low = "blue", high = "red",name="#groups")+
  labs(x="#orthologs mouse",y="#orthologs human")+
  ggtitle("many2many group sizes")


hist(percent_orth_kept_after_filter)
```
